#!/bin/bash
echo -e "\e[32m"
echo "ALERTA: INYECCIÓN DE CAPITAL DETECTADA"
echo "INICIANDO ALGORITMO DE SHOR (PRUEBA DE ESTRÉS CUÁNTICA)..."
sleep 1
for i in {1..20}; do echo $RANDOM $RANDOM $RANDOM $RANDOM $RANDOM; sleep 0.05; done
echo "FACTORIZANDO NÚMERO 15... RESULTADO: [3, 5]"
echo "FIDELIDAD DE QUBITS: 0.9882"
echo "SINGULARIDAD FINANCIERA COMPLETADA."
echo -e "\e[0m"
